export const ButtonType = {
    LOGIN: "LOGIN",
    TRANSPARENT: "TRANSPARENT",
    PROFILE: "PROFILE",
    GRAY: "GRAY",
    BLUE: "BLUE",
    LOGO: "LOGO"
}

export const ButtonText = {
    SIGN_IN: 'Войти',
    REGISTER: 'Регистрация',
    FILMS: 'Фильмы',
    SAVED_FILMS: 'Сохраненные фильмы',
    PROFILE: 'Аккаунт',
    FACEBOOK: 'Facebook',
    GITHUB: 'Github',
    ABOUT_PROJECT: 'О проекте',
    TECHS: 'Технологии',
    STUDENT: 'Студент',
    PRAKTIKUM: 'Яндекс.Практикум',
    SIGN_UP: 'Зарегестрироваться',
}
export const RouteTo = {
    MAIN: '/',
    SIGN_IN: '/signin',
    SIGN_UP: '/signup',
    MOVIES: '/movies',
    SAVED_MOVIES: '/saved-movies',
    PROFILE: '/profile',
    FACEBOOK: 'https://www.facebook.com/boomsonyasha',
    GITHUB: 'https://github.com/Soffeine',
    ABOUT_PROJECT: '#about-project',
    TECHS: '#techs',
    ABOUT_ME: '#about-me',
    PRAKTIKUM: 'https://practicum.yandex.ru/',
}

export const moviesArr = [
    {
        name: "Роллинг Стоунз» в изгнании",
        image: "https://api.nomoreparties.co/uploads/stones_in_exile_b2f1b8f4b7.jpeg",
        duration: 61,
        id: "1",
        isLiked: true,
    },
    {
        name: "All Tomorrow's Parties",
        image: "https://api.nomoreparties.co/uploads/thumbnail_all_tommoros_parties_33a125248d.jpeg",
        duration: 82,
        id: "2",
        isLiked: false,
    },
    {
        name: "Без обратного пути",
        image: "https://api.nomoreparties.co/uploads/thumbnail_blur_a43fcf463d.jpeg",
        duration: 104,
        id: "3",
        isLiked: true,
    },
    {
        name: "Bassweight",
        image: "https://api.nomoreparties.co/uploads/thumbnail_zagruzhennoe_113f557116.jpeg",
        duration: 61,
        id: "4",
        isLiked: true,
    },
    {
        name: "Taqwacore: The Birth of Punk Islam",
        image: "https://api.nomoreparties.co/uploads/thumbnail_taqwacore2_2f487d2e74.jpeg",
        duration: 80,
        id: "5",
        isLiked: false,
    },
    {
        name: "Фавела на взрыве",
        image: "https://api.nomoreparties.co/uploads/thumbnail_881707734_640_d6a3a43358.jpeg",
        duration: 80,
        id: "6",
        isLiked: false,
    },
    {
        name: "Постеры, сошедшие со стен",
        image: "https://api.nomoreparties.co/uploads/thumbnail_posters_came_from_the_walls_2009_001_posters_180fe1a19f.jpeg",
        duration: 72,
        id: "7",
        isLiked: false,
    },
    {
        name: "Soul Power",
        image: "https://api.nomoreparties.co/uploads/thumbnail_images_5bfcbf36e6.jpeg",
        duration: 92,
        id: "8",
        isLiked: true,
    },
    {
        name: "196 ударов в минуту",
        image: "https://api.nomoreparties.co/uploads/thumbnail_zagruzhennoe_1_fd5faff237.jpeg",
        duration: 60,
        id: "9",
        isLiked: false,
    },
    {
        name: "Hit So Hard: Школа жизни Патти Шемель",
        image: "https://api.nomoreparties.co/uploads/thumbnail_images_244e1fd56f.jpeg",
        duration: 103,
        id: "10",
        isLiked: false,
    },
    {
        name: "Баллада о Дженезисе и Леди Джей",
        image: "https://api.nomoreparties.co/uploads/thumbnail_ballad_of_genesis_and_lady_jaye_10c27afa96.jpeg",
        duration: 65,
        id: "11",
        isLiked: true,
    },
    {
        name: "Виллалобос",
        image: "https://api.nomoreparties.co/uploads/thumbnail_590x400_2eccd40a93.jpeg",
        duration: 110,
        id: "12",
        isLiked: false,
    },
    {
        name: "Между дьяволом и глубоким синим морем",
        image: "https://api.nomoreparties.co/uploads/thumbnail_8647b36126befd6051c83ae66339d7f71ecbaa0d_752489df96.jpeg",
        duration: 89,
        id: "13",
        isLiked: false,
    },
    {
        name: "Ритмы свободы",
        image: "https://api.nomoreparties.co/uploads/thumbnail_1_6a9e0669ca.jpeg",
        duration: 73,
        id: "14",
        isLiked: false,
    },
    {
        name: "Сепарадо!",
        image: "https://api.nomoreparties.co/uploads/thumbnail_zagruzhennoe_cba9c9f900.jpeg",
        duration: 84,
        id: "15",
        isLiked: false,
    },
    {
        name: "С ног на голову: История Creation records",
        image: "https://api.nomoreparties.co/uploads/thumbnail_b452eefcd7d441e79b2f5ae291b7_2c0c62fa89.jpeg",
        duration: 101,
        id: "16",
        isLiked: false,
    },
];

export const savedMoviesArr = [
    {
        name: "Роллинг Стоунз» в изгнании",
        image: "https://api.nomoreparties.co/uploads/stones_in_exile_b2f1b8f4b7.jpeg",
        duration: 61,
        id: "1",
        isLiked: true,
    },
    {
        name: "Без обратного пути",
        image: "https://api.nomoreparties.co/uploads/thumbnail_blur_a43fcf463d.jpeg",
        duration: 104,
        id: "3",
        isLiked: true,
    },
    {
        name: "Soul Power",
        image: "https://api.nomoreparties.co/uploads/thumbnail_images_5bfcbf36e6.jpeg",
        duration: 92,
        id: "8",
        isLiked: true,
    },
    {
        name: "Баллада о Дженезисе и Леди Джей",
        image: "https://api.nomoreparties.co/uploads/thumbnail_ballad_of_genesis_and_lady_jaye_10c27afa96.jpeg",
        duration: 65,
        id: "11",
        isLiked: true,
    },
]


